const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const User = require('../models/User');
const emailService = require('../utils/emailService');

const generateToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: '30d' });
};

const registerUser = async (req, res) => {
  console.log("--- New Registration Attempt ---");
  console.log("Body:", req.body);
  console.log("File:", req.file ? "Present" : "Missing");

  try {
    if (!req.body) {
      console.error("Error: req.body is undefined");
      return res.status(400).json({ message: 'Request body is missing.' });
    }
    const body = req.body || {};
    const { name, email, role, shopName, phone, address } = body;
    const idProof = req.file ? req.file.path : null;
    
    // Server-side validation: ID Proof is mandatory
    if (!idProof) {
      console.error("Error: idProof is missing (file upload failed or not provided)");
      return res.status(400).json({ message: 'License / ID Proof is mandatory.' });
    }

    if (role === 'admin') {
      return res.status(403).json({ message: 'Administrator registration is disabled. Please contact the system owner.' });
    }

    const userExists = await User.findOne({ email });
    if (userExists) return res.status(400).json({ message: 'User already exists' });

    const status = 'pending'; // All new pharmacies/distributors are pending

    // Create user without password (will be generated by admin later)
    const user = await User.create({ name, email, role, shopName, phone, address, status, idProof });

    if (user) {
      // Auto-create role-specific profile document
      if (role === 'pharmacy' || role === 'branch_manager' || role === 'pharmacist') {
        const PharmacyProfile = require('../models/PharmacyProfile');
        const profile = await PharmacyProfile.create({
          userId: user._id,
          pharmacyName: shopName || name,
          address: address || ''
        });
        user.pharmacyProfile = profile._id;
        await user.save();
      } else if (role === 'distributor') {
        const DistributorProfile = require('../models/DistributorProfile');
        const profile = await DistributorProfile.create({
          user: user._id,
          companyName: shopName || name,
          phone: phone || '',
          address: address || ''
        });
        user.distributorProfile = profile._id;
        await user.save();
      }

      // Send Registration Pending Email to User
      try {
        await emailService.sendRegistrationPendingEmail(user);
      } catch (err) {
        console.error("Registration pending email failed", err);
      }

      // Notify Global/System Admin of new registration
      try {
        await emailService.sendNewRegistrationAlert(process.env.EMAIL_USER, user);
      } catch (err) {
        console.error("Admin registration alert failed", err);
      }

      return res.status(201).json({ 
        message: 'Registration successful. Waiting for admin approval.',
        pending: true 
      });
    } else {
      res.status(400).json({ message: 'Invalid user data' });
    }
  } catch (error) {
    console.error("Registration Error:", error);
    res.status(500).json({ message: error.message || "Internal Server Error" });
  }
};

const loginUser = async (req, res) => {
  const { email, password } = req.body;
  try {
    // 1. Check for Hardcoded Admin in .env
    if (email === process.env.ADMIN_EMAIL && password === process.env.ADMIN_PASSWORD) {
      let admin = await User.findOne({ email: process.env.ADMIN_EMAIL, role: 'admin' });
      
      // Auto-create/sync hardcoded admin in DB if it doesn't exist
      if (!admin) {
        admin = await User.create({
          name: 'Global Administrator',
          email: process.env.ADMIN_EMAIL,
          password: process.env.ADMIN_PASSWORD,
          role: 'admin',
          status: 'approved'
        });
      }

      return res.json({
        _id: admin._id,
        name: admin.name,
        email: admin.email,
        role: admin.role,
        token: generateToken(admin._id),
      });
    }

    // 2. Normal User Login
    const user = await User.findOne({ email });
    if (user && (await user.matchPassword(password))) {
      if (user.status === 'pending') {
        return res.status(403).json({ message: 'Your account is pending admin approval. You will receive an email once approved.' });
      }
      if (user.status === 'rejected') {
        return res.status(403).json({ message: 'Your account application has been rejected.' });
      }

      res.json({
        _id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        token: generateToken(user._id),
      });
    } else {
      res.status(401).json({ message: 'Invalid email or password' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

const forgotPassword = async (req, res) => {
  const { email } = req.body;
  try {
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(404).json({ message: 'No account found with this email.' });
    }

    // Generate 6-digit OTP
    const otp = Math.floor(100000 + Math.random() * 900000).toString();
    user.otp = otp;
    user.otpExpires = Date.now() + 600000; // 10 minutes

    await user.save();

    // Send OTP Email
    try {
      await emailService.sendPasswordResetOTP(user, otp);
      res.json({ message: 'A 6-digit OTP has been sent to your email.' });
    } catch (err) {
      user.otp = undefined;
      user.otpExpires = undefined;
      await user.save();
      res.status(500).json({ message: 'Email could not be sent' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

const resetPassword = async (req, res) => {
  const { email, otp, newPassword } = req.body;
  try {
    const user = await User.findOne({ 
      email, 
      otp, 
      otpExpires: { $gt: Date.now() } 
    });

    if (!user) {
      return res.status(400).json({ message: 'Invalid or expired OTP.' });
    }

    // Set new password (the pre-save hook will hash it)
    user.password = newPassword;
    user.otp = undefined;
    user.otpExpires = undefined;
    await user.save();

    try {
      await emailService.sendPasswordChanged(user);
    } catch (err) {
      console.error("Password change notification failed", err);
    }

    res.json({ message: 'Password has been successfully reset. Please log in.' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = { registerUser, loginUser, forgotPassword, resetPassword };
